version: '3.8'

services:

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - common-net
    volumes:
      - ./rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
      - ./rabbitmq/definitions.json:/etc/rabbitmq/definitions.json:ro

  authentication-service:
    image: authentication-service
    build: ./authentication-service
    restart: on-failure
    ports:
      - "8082:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/users
      SPRING_DATASOURCE_USERNAME: admin-user
      SPRING_DATASOURCE_PASSWORD: admin_user_password
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://mysqldb:3306/users",
        "spring.datasource.username" : "admin-user",
        "spring.datasource.password" : "admin_user_password",
        "spring.jpa.hibernate.ddl-auto" : "none",
        "spring.jpa.database":"mysql",
        "spring.datasource.initialization-mode":"always",
        "spring.jpa.defer-datasource-initialization":"true",
        "logging.level.org.hibernate.type.descriptor.sql.BasicBinder":"TRACE",
        "jwt.symmetric.key":"01234567890123456789012345678901"
        }'
    networks:
      - common-net

    depends_on:
      - mysqldb

  database-service:
    image: database-service
    build: ./database-service
    restart: on-failure
    ports:
      - "8083:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/users
      SPRING_DATASOURCE_USERNAME: admin-user
      SPRING_DATASOURCE_PASSWORD: admin_user_password
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://mysqldb:3306/users",
        "spring.datasource.username" : "admin-user",
        "spring.datasource.password" : "admin_user_password",
        "spring.jpa.hibernate.ddl-auto" : "none",
        "spring.jpa.database":"mysql",
        "spring.datasource.initialization-mode":"always",
        "spring.jpa.defer-datasource-initialization":"true",
        "logging.level.org.hibernate.type.descriptor.sql.BasicBinder":"TRACE",
        "jwt.symmetric.key":"01234567890123456789012345678901",
        "queue.rabbitmq.listener.name": "user_queue_instance_1",
        "queue.rabbitmq.listener.anomaly":"anomaly_queue_instance_1",
        "binding.rabbitmq.key" : "user_key_queue_1",
        "binding.rabbitmq.anomaly.key":"anomalies_key",
        "spring.rabbitmq.host":"rabbitmq",
        "spring.rabbitmq.port":"5672",
        "spring.rabbitmq.username":"guest",
        "spring.rabbitmq.password":"guest"
        }'
    networks:
      - common-net
    depends_on:
      - mysqldb

  userservice:
    image: userservice
    build: ./userservice
    ports:
      - "8081:8080"
    environment:
      SPRING_APPLICATION_JSON: '{
        "jwt.symmetric.key":"01234567890123456789012345678901",
        "queue.rabbitmq.listener.name": "user_queue_instance_1",
        "queue.rabbitmq.listener.anomaly":"anomaly_queue_instance_1",
        "binding.rabbitmq.key" : "user_key_queue_1",
        "binding.rabbitmq.anomaly.key":"anomalies_key",
        "spring.rabbitmq.host":"rabbitmq",
        "spring.rabbitmq.port":"5672",
        "spring.rabbitmq.username":"guest",
        "spring.rabbitmq.password":"guest"
        }'
    networks:
      - common-net

  user-ui:
    image: user-ui
    build: ./user-manager-ui
    ports:
    - 80:4200
    networks:
      - common-net

  mysqldb:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: users
      MYSQL_USER: admin-user
      MYSQL_PASSWORD: admin_user_password
      MYSQL_INITDB: /docker-entrypoint-initdb.d
    networks:
      - common-net
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - ./mysql-init:/docker-entrypoint-initdb.d
networks:
  common-net: